// Copied from https://github.com/luxfi/netrunner/blob/v1.3.0/rpcpb/rpc.proto
// without gRPC gateway dependency

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: rpcpb/rpc.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ClusterInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NodeNames   []string               `protobuf:"bytes,1,rep,name=node_names,json=nodeNames,proto3" json:"node_names,omitempty"`
	NodeInfos   map[string]*NodeInfo   `protobuf:"bytes,2,rep,name=node_infos,json=nodeInfos,proto3" json:"node_infos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Pid         int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	RootDataDir string                 `protobuf:"bytes,4,opt,name=root_data_dir,json=rootDataDir,proto3" json:"root_data_dir,omitempty"`
	Healthy     bool                   `protobuf:"varint,5,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Maps from the node ID to its attached peer infos.
	AttachedPeerInfos map[string]*ListOfAttachedPeerInfo `protobuf:"bytes,6,rep,name=attached_peer_infos,json=attachedPeerInfos,proto3" json:"attached_peer_infos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Set to "true" once custom blockchains are ready.
	CustomChainsHealthy bool `protobuf:"varint,7,opt,name=custom_chains_healthy,json=customChainsHealthy,proto3" json:"custom_chains_healthy,omitempty"`
	// The map of blockchain IDs in "ids.ID" format to its blockchain information.
	CustomChains  map[string]*CustomChainInfo `protobuf:"bytes,8,rep,name=custom_chains,json=customChains,proto3" json:"custom_chains,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Subnets       []string                    `protobuf:"bytes,9,rep,name=subnets,proto3" json:"subnets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfo) Reset() {
	*x = ClusterInfo{}
	mi := &file_rpcpb_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfo) ProtoMessage() {}

func (x *ClusterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfo.ProtoReflect.Descriptor instead.
func (*ClusterInfo) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterInfo) GetNodeNames() []string {
	if x != nil {
		return x.NodeNames
	}
	return nil
}

func (x *ClusterInfo) GetNodeInfos() map[string]*NodeInfo {
	if x != nil {
		return x.NodeInfos
	}
	return nil
}

func (x *ClusterInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ClusterInfo) GetRootDataDir() string {
	if x != nil {
		return x.RootDataDir
	}
	return ""
}

func (x *ClusterInfo) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ClusterInfo) GetAttachedPeerInfos() map[string]*ListOfAttachedPeerInfo {
	if x != nil {
		return x.AttachedPeerInfos
	}
	return nil
}

func (x *ClusterInfo) GetCustomChainsHealthy() bool {
	if x != nil {
		return x.CustomChainsHealthy
	}
	return false
}

func (x *ClusterInfo) GetCustomChains() map[string]*CustomChainInfo {
	if x != nil {
		return x.CustomChains
	}
	return nil
}

func (x *ClusterInfo) GetSubnets() []string {
	if x != nil {
		return x.Subnets
	}
	return nil
}

type CustomChainInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Blockchain name given to the create blockchain TX
	// Currently used to keep a record of the VM name,
	// which is not saved anywhere and can't be recovered from VM ID
	ChainName string `protobuf:"bytes,1,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	// VM ID in "ids.ID" format.
	VmId string `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	// Create subnet transaction ID -- subnet ID.
	// The subnet ID must be whitelisted by the lux node.
	SubnetId string `protobuf:"bytes,3,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	// Create blockchain transaction ID -- blockchain ID>
	// The blockchain ID is used for RPC endpoints.
	ChainId       string `protobuf:"bytes,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomChainInfo) Reset() {
	*x = CustomChainInfo{}
	mi := &file_rpcpb_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomChainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomChainInfo) ProtoMessage() {}

func (x *CustomChainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomChainInfo.ProtoReflect.Descriptor instead.
func (*CustomChainInfo) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *CustomChainInfo) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *CustomChainInfo) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CustomChainInfo) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *CustomChainInfo) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type NodeInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExecPath           string                 `protobuf:"bytes,2,opt,name=exec_path,json=execPath,proto3" json:"exec_path,omitempty"`
	Uri                string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Id                 string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	LogDir             string                 `protobuf:"bytes,5,opt,name=log_dir,json=logDir,proto3" json:"log_dir,omitempty"`
	DbDir              string                 `protobuf:"bytes,6,opt,name=db_dir,json=dbDir,proto3" json:"db_dir,omitempty"`
	PluginDir          string                 `protobuf:"bytes,7,opt,name=plugin_dir,json=pluginDir,proto3" json:"plugin_dir,omitempty"`
	WhitelistedSubnets string                 `protobuf:"bytes,8,opt,name=whitelisted_subnets,json=whitelistedSubnets,proto3" json:"whitelisted_subnets,omitempty"`
	Config             []byte                 `protobuf:"bytes,9,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_rpcpb_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetExecPath() string {
	if x != nil {
		return x.ExecPath
	}
	return ""
}

func (x *NodeInfo) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetLogDir() string {
	if x != nil {
		return x.LogDir
	}
	return ""
}

func (x *NodeInfo) GetDbDir() string {
	if x != nil {
		return x.DbDir
	}
	return ""
}

func (x *NodeInfo) GetPluginDir() string {
	if x != nil {
		return x.PluginDir
	}
	return ""
}

func (x *NodeInfo) GetWhitelistedSubnets() string {
	if x != nil {
		return x.WhitelistedSubnets
	}
	return ""
}

func (x *NodeInfo) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type AttachedPeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachedPeerInfo) Reset() {
	*x = AttachedPeerInfo{}
	mi := &file_rpcpb_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachedPeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachedPeerInfo) ProtoMessage() {}

func (x *AttachedPeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachedPeerInfo.ProtoReflect.Descriptor instead.
func (*AttachedPeerInfo) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *AttachedPeerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListOfAttachedPeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*AttachedPeerInfo    `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOfAttachedPeerInfo) Reset() {
	*x = ListOfAttachedPeerInfo{}
	mi := &file_rpcpb_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOfAttachedPeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfAttachedPeerInfo) ProtoMessage() {}

func (x *ListOfAttachedPeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfAttachedPeerInfo.ProtoReflect.Descriptor instead.
func (*ListOfAttachedPeerInfo) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *ListOfAttachedPeerInfo) GetPeers() []*AttachedPeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type StartRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExecPath           string                 `protobuf:"bytes,1,opt,name=exec_path,json=execPath,proto3" json:"exec_path,omitempty"`
	NumNodes           *uint32                `protobuf:"varint,2,opt,name=num_nodes,json=numNodes,proto3,oneof" json:"num_nodes,omitempty"`
	WhitelistedSubnets *string                `protobuf:"bytes,3,opt,name=whitelisted_subnets,json=whitelistedSubnets,proto3,oneof" json:"whitelisted_subnets,omitempty"`
	GlobalNodeConfig   *string                `protobuf:"bytes,4,opt,name=global_node_config,json=globalNodeConfig,proto3,oneof" json:"global_node_config,omitempty"`
	// Used for both database and log files.
	RootDataDir *string `protobuf:"bytes,5,opt,name=root_data_dir,json=rootDataDir,proto3,oneof" json:"root_data_dir,omitempty"`
	// Build directory that contains the subdir 'plugins' from which to load all custom VM executables.
	// If not specified, will be derived from the exec_path (its basedir)
	PluginDir *string `protobuf:"bytes,6,opt,name=plugin_dir,json=pluginDir,proto3,oneof" json:"plugin_dir,omitempty"`
	// The list of:
	// - custom chain's VM name
	// - genesis file path
	// - (optional) subnet id to use.
	// - chain config file path
	// - network upgrade file path
	//
	// subnet id must be always nil when using StartRequest, as the network is empty and has no preloaded
	// subnet ids available.
	//
	// The matching file with the name in "ids.ID" format must exist.
	// e.g., ids.ToID(hashing.ComputeHash256("subnetevm")).String()
	// e.g., subnet-cli create VMID subnetevm
	//
	// If this field is set to none (by default), the node/netrunner
	// does not install the custom chain and does not create the subnet,
	// even if the VM binary exists on the local plugins directory.
	BlockchainSpecs   []*BlockchainSpec `protobuf:"bytes,7,rep,name=blockchain_specs,json=blockchainSpecs,proto3" json:"blockchain_specs,omitempty"`
	CustomNodeConfigs map[string]string `protobuf:"bytes,8,rep,name=custom_node_configs,json=customNodeConfigs,proto3" json:"custom_node_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Map of chain name to config file contents.
	// If specified, will create a file "chainname/config.json" with
	// the contents provided here.
	ChainConfigs map[string]string `protobuf:"bytes,9,rep,name=chain_configs,json=chainConfigs,proto3" json:"chain_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Map of chain name to upgrade file contents.
	// If specified, will create a file "chainname/upgrade.json" with
	// the contents provided here.
	UpgradeConfigs map[string]string `protobuf:"bytes,10,rep,name=upgrade_configs,json=upgradeConfigs,proto3" json:"upgrade_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// reassign default/custom ports if they are already taken
	ReassignPortsIfUsed *bool `protobuf:"varint,11,opt,name=reassign_ports_if_used,json=reassignPortsIfUsed,proto3,oneof" json:"reassign_ports_if_used,omitempty"`
	// use dynamic ports instead of default ones
	DynamicPorts  *bool `protobuf:"varint,12,opt,name=dynamic_ports,json=dynamicPorts,proto3,oneof" json:"dynamic_ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *StartRequest) GetExecPath() string {
	if x != nil {
		return x.ExecPath
	}
	return ""
}

func (x *StartRequest) GetNumNodes() uint32 {
	if x != nil && x.NumNodes != nil {
		return *x.NumNodes
	}
	return 0
}

func (x *StartRequest) GetWhitelistedSubnets() string {
	if x != nil && x.WhitelistedSubnets != nil {
		return *x.WhitelistedSubnets
	}
	return ""
}

func (x *StartRequest) GetGlobalNodeConfig() string {
	if x != nil && x.GlobalNodeConfig != nil {
		return *x.GlobalNodeConfig
	}
	return ""
}

func (x *StartRequest) GetRootDataDir() string {
	if x != nil && x.RootDataDir != nil {
		return *x.RootDataDir
	}
	return ""
}

func (x *StartRequest) GetPluginDir() string {
	if x != nil && x.PluginDir != nil {
		return *x.PluginDir
	}
	return ""
}

func (x *StartRequest) GetBlockchainSpecs() []*BlockchainSpec {
	if x != nil {
		return x.BlockchainSpecs
	}
	return nil
}

func (x *StartRequest) GetCustomNodeConfigs() map[string]string {
	if x != nil {
		return x.CustomNodeConfigs
	}
	return nil
}

func (x *StartRequest) GetChainConfigs() map[string]string {
	if x != nil {
		return x.ChainConfigs
	}
	return nil
}

func (x *StartRequest) GetUpgradeConfigs() map[string]string {
	if x != nil {
		return x.UpgradeConfigs
	}
	return nil
}

func (x *StartRequest) GetReassignPortsIfUsed() bool {
	if x != nil && x.ReassignPortsIfUsed != nil {
		return *x.ReassignPortsIfUsed
	}
	return false
}

func (x *StartRequest) GetDynamicPorts() bool {
	if x != nil && x.DynamicPorts != nil {
		return *x.DynamicPorts
	}
	return false
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterInfo   *ClusterInfo           `protobuf:"bytes,1,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *StartResponse) GetClusterInfo() *ClusterInfo {
	if x != nil {
		return x.ClusterInfo
	}
	return nil
}

type BlockchainSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VmName         string                 `protobuf:"bytes,1,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	Genesis        string                 `protobuf:"bytes,2,opt,name=genesis,proto3" json:"genesis,omitempty"`
	SubnetId       *string                `protobuf:"bytes,3,opt,name=subnet_id,json=subnetId,proto3,oneof" json:"subnet_id,omitempty"`
	ChainConfig    string                 `protobuf:"bytes,4,opt,name=chain_config,json=chainConfig,proto3" json:"chain_config,omitempty"`
	NetworkUpgrade string                 `protobuf:"bytes,5,opt,name=network_upgrade,json=networkUpgrade,proto3" json:"network_upgrade,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockchainSpec) Reset() {
	*x = BlockchainSpec{}
	mi := &file_rpcpb_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainSpec) ProtoMessage() {}

func (x *BlockchainSpec) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainSpec.ProtoReflect.Descriptor instead.
func (*BlockchainSpec) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *BlockchainSpec) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *BlockchainSpec) GetGenesis() string {
	if x != nil {
		return x.Genesis
	}
	return ""
}

func (x *BlockchainSpec) GetSubnetId() string {
	if x != nil && x.SubnetId != nil {
		return *x.SubnetId
	}
	return ""
}

func (x *BlockchainSpec) GetChainConfig() string {
	if x != nil {
		return x.ChainConfig
	}
	return ""
}

func (x *BlockchainSpec) GetNetworkUpgrade() string {
	if x != nil {
		return x.NetworkUpgrade
	}
	return ""
}

type CreateBlockchainsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of:
	// - custom chain's VM name
	// - genesis file path
	// - (optional) subnet id to use.
	// - chain config file path
	// - network upgrade file path
	//
	// The matching file with the name in "ids.ID" format must exist.
	// e.g., ids.ToID(hashing.ComputeHash256("subnetevm")).String()
	// e.g., subnet-cli create VMID subnetevm
	//
	// If this field is set to none (by default), the node/netrunner
	// will return error
	BlockchainSpecs []*BlockchainSpec `protobuf:"bytes,1,rep,name=blockchain_specs,json=blockchainSpecs,proto3" json:"blockchain_specs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateBlockchainsRequest) Reset() {
	*x = CreateBlockchainsRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlockchainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlockchainsRequest) ProtoMessage() {}

func (x *CreateBlockchainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlockchainsRequest.ProtoReflect.Descriptor instead.
func (*CreateBlockchainsRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *CreateBlockchainsRequest) GetBlockchainSpecs() []*BlockchainSpec {
	if x != nil {
		return x.BlockchainSpecs
	}
	return nil
}

type CreateBlockchainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterInfo   *ClusterInfo           `protobuf:"bytes,1,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlockchainsResponse) Reset() {
	*x = CreateBlockchainsResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlockchainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlockchainsResponse) ProtoMessage() {}

func (x *CreateBlockchainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlockchainsResponse.ProtoReflect.Descriptor instead.
func (*CreateBlockchainsResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *CreateBlockchainsResponse) GetClusterInfo() *ClusterInfo {
	if x != nil {
		return x.ClusterInfo
	}
	return nil
}

type CreateSubnetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumSubnets    *uint32                `protobuf:"varint,1,opt,name=num_subnets,json=numSubnets,proto3,oneof" json:"num_subnets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubnetsRequest) Reset() {
	*x = CreateSubnetsRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubnetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubnetsRequest) ProtoMessage() {}

func (x *CreateSubnetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubnetsRequest.ProtoReflect.Descriptor instead.
func (*CreateSubnetsRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *CreateSubnetsRequest) GetNumSubnets() uint32 {
	if x != nil && x.NumSubnets != nil {
		return *x.NumSubnets
	}
	return 0
}

type CreateSubnetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterInfo   *ClusterInfo           `protobuf:"bytes,1,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubnetsResponse) Reset() {
	*x = CreateSubnetsResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubnetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubnetsResponse) ProtoMessage() {}

func (x *CreateSubnetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubnetsResponse.ProtoReflect.Descriptor instead.
func (*CreateSubnetsResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *CreateSubnetsResponse) GetClusterInfo() *ClusterInfo {
	if x != nil {
		return x.ClusterInfo
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{14}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterInfo   *ClusterInfo           `protobuf:"bytes,1,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *HealthResponse) GetClusterInfo() *ClusterInfo {
	if x != nil {
		return x.ClusterInfo
	}
	return nil
}

type URIsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URIsRequest) Reset() {
	*x = URIsRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URIsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URIsRequest) ProtoMessage() {}

func (x *URIsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URIsRequest.ProtoReflect.Descriptor instead.
func (*URIsRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{16}
}

type URIsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uris          []string               `protobuf:"bytes,1,rep,name=uris,proto3" json:"uris,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URIsResponse) Reset() {
	*x = URIsResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URIsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URIsResponse) ProtoMessage() {}

func (x *URIsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URIsResponse.ProtoReflect.Descriptor instead.
func (*URIsResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *URIsResponse) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{18}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterInfo   *ClusterInfo           `protobuf:"bytes,1,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{19}
}

func (x *StatusResponse) GetClusterInfo() *ClusterInfo {
	if x != nil {
		return x.ClusterInfo
	}
	return nil
}

type StreamStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PushInterval  int64                  `protobuf:"varint,1,opt,name=push_interval,json=pushInterval,proto3" json:"push_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStatusRequest) Reset() {
	*x = StreamStatusRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatusRequest) ProtoMessage() {}

func (x *StreamStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatusRequest.ProtoReflect.Descriptor instead.
func (*StreamStatusRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{20}
}

func (x *StreamStatusRequest) GetPushInterval() int64 {
	if x != nil {
		return x.PushInterval
	}
	return 0
}

type StreamStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterInfo   *ClusterInfo           `protobuf:"bytes,1,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStatusResponse) Reset() {
	*x = StreamStatusResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatusResponse) ProtoMessage() {}

func (x *StreamStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatusResponse.ProtoReflect.Descriptor instead.
func (*StreamStatusResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{21}
}

func (x *StreamStatusResponse) GetClusterInfo() *ClusterInfo {
	if x != nil {
		return x.ClusterInfo
	}
	return nil
}

type RestartNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must be a valid node name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional fields are set to the previous values if empty.
	ExecPath           *string `protobuf:"bytes,2,opt,name=exec_path,json=execPath,proto3,oneof" json:"exec_path,omitempty"`
	WhitelistedSubnets *string `protobuf:"bytes,3,opt,name=whitelisted_subnets,json=whitelistedSubnets,proto3,oneof" json:"whitelisted_subnets,omitempty"`
	// Map of chain name to config file contents.
	// If specified, will create a file "chainname/config.json" with
	// the contents provided here.
	ChainConfigs map[string]string `protobuf:"bytes,4,rep,name=chain_configs,json=chainConfigs,proto3" json:"chain_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Map of chain name to config file contents.
	// If specified, will create a file "chainname/upgrade.json" with
	// the contents provided here.
	UpgradeConfigs map[string]string `protobuf:"bytes,5,rep,name=upgrade_configs,json=upgradeConfigs,proto3" json:"upgrade_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RestartNodeRequest) Reset() {
	*x = RestartNodeRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartNodeRequest) ProtoMessage() {}

func (x *RestartNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartNodeRequest.ProtoReflect.Descriptor instead.
func (*RestartNodeRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{22}
}

func (x *RestartNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestartNodeRequest) GetExecPath() string {
	if x != nil && x.ExecPath != nil {
		return *x.ExecPath
	}
	return ""
}

func (x *RestartNodeRequest) GetWhitelistedSubnets() string {
	if x != nil && x.WhitelistedSubnets != nil {
		return *x.WhitelistedSubnets
	}
	return ""
}

func (x *RestartNodeRequest) GetChainConfigs() map[string]string {
	if x != nil {
		return x.ChainConfigs
	}
	return nil
}

func (x *RestartNodeRequest) GetUpgradeConfigs() map[string]string {
	if x != nil {
		return x.UpgradeConfigs
	}
	return nil
}

type RestartNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterInfo   *ClusterInfo           `protobuf:"bytes,1,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartNodeResponse) Reset() {
	*x = RestartNodeResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartNodeResponse) ProtoMessage() {}

func (x *RestartNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartNodeResponse.ProtoReflect.Descriptor instead.
func (*RestartNodeResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{23}
}

func (x *RestartNodeResponse) GetClusterInfo() *ClusterInfo {
	if x != nil {
		return x.ClusterInfo
	}
	return nil
}

type RemoveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterInfo   *ClusterInfo           `protobuf:"bytes,1,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeResponse) Reset() {
	*x = RemoveNodeResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResponse) ProtoMessage() {}

func (x *RemoveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveNodeResponse) GetClusterInfo() *ClusterInfo {
	if x != nil {
		return x.ClusterInfo
	}
	return nil
}

type AddNodeRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExecPath   string                 `protobuf:"bytes,2,opt,name=exec_path,json=execPath,proto3" json:"exec_path,omitempty"`
	NodeConfig *string                `protobuf:"bytes,3,opt,name=node_config,json=nodeConfig,proto3,oneof" json:"node_config,omitempty"`
	// Map of chain name to config file contents.
	// If specified, will create a file "chainname/config.json" with
	// the contents provided here.
	ChainConfigs map[string]string `protobuf:"bytes,4,rep,name=chain_configs,json=chainConfigs,proto3" json:"chain_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Map of chain name to config file contents.
	// If specified, will create a file "chainname/upgrade.json" with
	// the contents provided here.
	UpgradeConfigs map[string]string `protobuf:"bytes,5,rep,name=upgrade_configs,json=upgradeConfigs,proto3" json:"upgrade_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddNodeRequest) Reset() {
	*x = AddNodeRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeRequest) ProtoMessage() {}

func (x *AddNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeRequest.ProtoReflect.Descriptor instead.
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{26}
}

func (x *AddNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddNodeRequest) GetExecPath() string {
	if x != nil {
		return x.ExecPath
	}
	return ""
}

func (x *AddNodeRequest) GetNodeConfig() string {
	if x != nil && x.NodeConfig != nil {
		return *x.NodeConfig
	}
	return ""
}

func (x *AddNodeRequest) GetChainConfigs() map[string]string {
	if x != nil {
		return x.ChainConfigs
	}
	return nil
}

func (x *AddNodeRequest) GetUpgradeConfigs() map[string]string {
	if x != nil {
		return x.UpgradeConfigs
	}
	return nil
}

type AddNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterInfo   *ClusterInfo           `protobuf:"bytes,1,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeResponse) Reset() {
	*x = AddNodeResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeResponse) ProtoMessage() {}

func (x *AddNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeResponse.ProtoReflect.Descriptor instead.
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{27}
}

func (x *AddNodeResponse) GetClusterInfo() *ClusterInfo {
	if x != nil {
		return x.ClusterInfo
	}
	return nil
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{28}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterInfo   *ClusterInfo           `protobuf:"bytes,1,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{29}
}

func (x *StopResponse) GetClusterInfo() *ClusterInfo {
	if x != nil {
		return x.ClusterInfo
	}
	return nil
}

type AttachPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachPeerRequest) Reset() {
	*x = AttachPeerRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPeerRequest) ProtoMessage() {}

func (x *AttachPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPeerRequest.ProtoReflect.Descriptor instead.
func (*AttachPeerRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{30}
}

func (x *AttachPeerRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type AttachPeerResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClusterInfo      *ClusterInfo           `protobuf:"bytes,1,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	AttachedPeerInfo *AttachedPeerInfo      `protobuf:"bytes,2,opt,name=attached_peer_info,json=attachedPeerInfo,proto3" json:"attached_peer_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AttachPeerResponse) Reset() {
	*x = AttachPeerResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPeerResponse) ProtoMessage() {}

func (x *AttachPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPeerResponse.ProtoReflect.Descriptor instead.
func (*AttachPeerResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{31}
}

func (x *AttachPeerResponse) GetClusterInfo() *ClusterInfo {
	if x != nil {
		return x.ClusterInfo
	}
	return nil
}

func (x *AttachPeerResponse) GetAttachedPeerInfo() *AttachedPeerInfo {
	if x != nil {
		return x.AttachedPeerInfo
	}
	return nil
}

type SendOutboundMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Op            uint32                 `protobuf:"varint,3,opt,name=op,proto3" json:"op,omitempty"`
	Bytes         []byte                 `protobuf:"bytes,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOutboundMessageRequest) Reset() {
	*x = SendOutboundMessageRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOutboundMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOutboundMessageRequest) ProtoMessage() {}

func (x *SendOutboundMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOutboundMessageRequest.ProtoReflect.Descriptor instead.
func (*SendOutboundMessageRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{32}
}

func (x *SendOutboundMessageRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *SendOutboundMessageRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *SendOutboundMessageRequest) GetOp() uint32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *SendOutboundMessageRequest) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type SendOutboundMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sent          bool                   `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOutboundMessageResponse) Reset() {
	*x = SendOutboundMessageResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOutboundMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOutboundMessageResponse) ProtoMessage() {}

func (x *SendOutboundMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOutboundMessageResponse.ProtoReflect.Descriptor instead.
func (*SendOutboundMessageResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{33}
}

func (x *SendOutboundMessageResponse) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

type SaveSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotName  string                 `protobuf:"bytes,1,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveSnapshotRequest) Reset() {
	*x = SaveSnapshotRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSnapshotRequest) ProtoMessage() {}

func (x *SaveSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSnapshotRequest.ProtoReflect.Descriptor instead.
func (*SaveSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{34}
}

func (x *SaveSnapshotRequest) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

type SaveSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotPath  string                 `protobuf:"bytes,1,opt,name=snapshot_path,json=snapshotPath,proto3" json:"snapshot_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveSnapshotResponse) Reset() {
	*x = SaveSnapshotResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSnapshotResponse) ProtoMessage() {}

func (x *SaveSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSnapshotResponse.ProtoReflect.Descriptor instead.
func (*SaveSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{35}
}

func (x *SaveSnapshotResponse) GetSnapshotPath() string {
	if x != nil {
		return x.SnapshotPath
	}
	return ""
}

type LoadSnapshotRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SnapshotName        string                 `protobuf:"bytes,1,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	ExecPath            *string                `protobuf:"bytes,2,opt,name=exec_path,json=execPath,proto3,oneof" json:"exec_path,omitempty"`
	PluginDir           *string                `protobuf:"bytes,3,opt,name=plugin_dir,json=pluginDir,proto3,oneof" json:"plugin_dir,omitempty"`
	RootDataDir         *string                `protobuf:"bytes,4,opt,name=root_data_dir,json=rootDataDir,proto3,oneof" json:"root_data_dir,omitempty"`
	ChainConfigs        map[string]string      `protobuf:"bytes,5,rep,name=chain_configs,json=chainConfigs,proto3" json:"chain_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpgradeConfigs      map[string]string      `protobuf:"bytes,6,rep,name=upgrade_configs,json=upgradeConfigs,proto3" json:"upgrade_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GlobalNodeConfig    *string                `protobuf:"bytes,7,opt,name=global_node_config,json=globalNodeConfig,proto3,oneof" json:"global_node_config,omitempty"`
	ReassignPortsIfUsed *bool                  `protobuf:"varint,8,opt,name=reassign_ports_if_used,json=reassignPortsIfUsed,proto3,oneof" json:"reassign_ports_if_used,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoadSnapshotRequest) Reset() {
	*x = LoadSnapshotRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSnapshotRequest) ProtoMessage() {}

func (x *LoadSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSnapshotRequest.ProtoReflect.Descriptor instead.
func (*LoadSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{36}
}

func (x *LoadSnapshotRequest) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

func (x *LoadSnapshotRequest) GetExecPath() string {
	if x != nil && x.ExecPath != nil {
		return *x.ExecPath
	}
	return ""
}

func (x *LoadSnapshotRequest) GetPluginDir() string {
	if x != nil && x.PluginDir != nil {
		return *x.PluginDir
	}
	return ""
}

func (x *LoadSnapshotRequest) GetRootDataDir() string {
	if x != nil && x.RootDataDir != nil {
		return *x.RootDataDir
	}
	return ""
}

func (x *LoadSnapshotRequest) GetChainConfigs() map[string]string {
	if x != nil {
		return x.ChainConfigs
	}
	return nil
}

func (x *LoadSnapshotRequest) GetUpgradeConfigs() map[string]string {
	if x != nil {
		return x.UpgradeConfigs
	}
	return nil
}

func (x *LoadSnapshotRequest) GetGlobalNodeConfig() string {
	if x != nil && x.GlobalNodeConfig != nil {
		return *x.GlobalNodeConfig
	}
	return ""
}

func (x *LoadSnapshotRequest) GetReassignPortsIfUsed() bool {
	if x != nil && x.ReassignPortsIfUsed != nil {
		return *x.ReassignPortsIfUsed
	}
	return false
}

type LoadSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterInfo   *ClusterInfo           `protobuf:"bytes,1,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadSnapshotResponse) Reset() {
	*x = LoadSnapshotResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSnapshotResponse) ProtoMessage() {}

func (x *LoadSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSnapshotResponse.ProtoReflect.Descriptor instead.
func (*LoadSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{37}
}

func (x *LoadSnapshotResponse) GetClusterInfo() *ClusterInfo {
	if x != nil {
		return x.ClusterInfo
	}
	return nil
}

type RemoveSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotName  string                 `protobuf:"bytes,1,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSnapshotRequest) Reset() {
	*x = RemoveSnapshotRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSnapshotRequest) ProtoMessage() {}

func (x *RemoveSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSnapshotRequest.ProtoReflect.Descriptor instead.
func (*RemoveSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{38}
}

func (x *RemoveSnapshotRequest) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

type RemoveSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSnapshotResponse) Reset() {
	*x = RemoveSnapshotResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSnapshotResponse) ProtoMessage() {}

func (x *RemoveSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSnapshotResponse.ProtoReflect.Descriptor instead.
func (*RemoveSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{39}
}

type GetSnapshotNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotNamesRequest) Reset() {
	*x = GetSnapshotNamesRequest{}
	mi := &file_rpcpb_rpc_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotNamesRequest) ProtoMessage() {}

func (x *GetSnapshotNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotNamesRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotNamesRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{40}
}

type GetSnapshotNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotNames []string               `protobuf:"bytes,1,rep,name=snapshot_names,json=snapshotNames,proto3" json:"snapshot_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotNamesResponse) Reset() {
	*x = GetSnapshotNamesResponse{}
	mi := &file_rpcpb_rpc_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotNamesResponse) ProtoMessage() {}

func (x *GetSnapshotNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_rpc_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotNamesResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotNamesResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_rpc_proto_rawDescGZIP(), []int{41}
}

func (x *GetSnapshotNamesResponse) GetSnapshotNames() []string {
	if x != nil {
		return x.SnapshotNames
	}
	return nil
}

var File_rpcpb_rpc_proto protoreflect.FileDescriptor

const file_rpcpb_rpc_proto_rawDesc = "" +
	"\n" +
	"\x0frpcpb/rpc.proto\x12\x05rpcpb\"\r\n" +
	"\vPingRequest\" \n" +
	"\fPingResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"\xbf\x05\n" +
	"\vClusterInfo\x12\x1d\n" +
	"\n" +
	"node_names\x18\x01 \x03(\tR\tnodeNames\x12@\n" +
	"\n" +
	"node_infos\x18\x02 \x03(\v2!.rpcpb.ClusterInfo.NodeInfosEntryR\tnodeInfos\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\"\n" +
	"\rroot_data_dir\x18\x04 \x01(\tR\vrootDataDir\x12\x18\n" +
	"\ahealthy\x18\x05 \x01(\bR\ahealthy\x12Y\n" +
	"\x13attached_peer_infos\x18\x06 \x03(\v2).rpcpb.ClusterInfo.AttachedPeerInfosEntryR\x11attachedPeerInfos\x122\n" +
	"\x15custom_chains_healthy\x18\a \x01(\bR\x13customChainsHealthy\x12I\n" +
	"\rcustom_chains\x18\b \x03(\v2$.rpcpb.ClusterInfo.CustomChainsEntryR\fcustomChains\x12\x18\n" +
	"\asubnets\x18\t \x03(\tR\asubnets\x1aM\n" +
	"\x0eNodeInfosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.rpcpb.NodeInfoR\x05value:\x028\x01\x1ac\n" +
	"\x16AttachedPeerInfosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.rpcpb.ListOfAttachedPeerInfoR\x05value:\x028\x01\x1aW\n" +
	"\x11CustomChainsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.rpcpb.CustomChainInfoR\x05value:\x028\x01\"}\n" +
	"\x0fCustomChainInfo\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x01 \x01(\tR\tchainName\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12\x1b\n" +
	"\tsubnet_id\x18\x03 \x01(\tR\bsubnetId\x12\x19\n" +
	"\bchain_id\x18\x04 \x01(\tR\achainId\"\xf5\x01\n" +
	"\bNodeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\texec_path\x18\x02 \x01(\tR\bexecPath\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x17\n" +
	"\alog_dir\x18\x05 \x01(\tR\x06logDir\x12\x15\n" +
	"\x06db_dir\x18\x06 \x01(\tR\x05dbDir\x12\x1d\n" +
	"\n" +
	"plugin_dir\x18\a \x01(\tR\tpluginDir\x12/\n" +
	"\x13whitelisted_subnets\x18\b \x01(\tR\x12whitelistedSubnets\x12\x16\n" +
	"\x06config\x18\t \x01(\fR\x06config\"\"\n" +
	"\x10AttachedPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x16ListOfAttachedPeerInfo\x12-\n" +
	"\x05peers\x18\x01 \x03(\v2\x17.rpcpb.AttachedPeerInfoR\x05peers\"\xf8\a\n" +
	"\fStartRequest\x12\x1b\n" +
	"\texec_path\x18\x01 \x01(\tR\bexecPath\x12 \n" +
	"\tnum_nodes\x18\x02 \x01(\rH\x00R\bnumNodes\x88\x01\x01\x124\n" +
	"\x13whitelisted_subnets\x18\x03 \x01(\tH\x01R\x12whitelistedSubnets\x88\x01\x01\x121\n" +
	"\x12global_node_config\x18\x04 \x01(\tH\x02R\x10globalNodeConfig\x88\x01\x01\x12'\n" +
	"\rroot_data_dir\x18\x05 \x01(\tH\x03R\vrootDataDir\x88\x01\x01\x12\"\n" +
	"\n" +
	"plugin_dir\x18\x06 \x01(\tH\x04R\tpluginDir\x88\x01\x01\x12@\n" +
	"\x10blockchain_specs\x18\a \x03(\v2\x15.rpcpb.BlockchainSpecR\x0fblockchainSpecs\x12Z\n" +
	"\x13custom_node_configs\x18\b \x03(\v2*.rpcpb.StartRequest.CustomNodeConfigsEntryR\x11customNodeConfigs\x12J\n" +
	"\rchain_configs\x18\t \x03(\v2%.rpcpb.StartRequest.ChainConfigsEntryR\fchainConfigs\x12P\n" +
	"\x0fupgrade_configs\x18\n" +
	" \x03(\v2'.rpcpb.StartRequest.UpgradeConfigsEntryR\x0eupgradeConfigs\x128\n" +
	"\x16reassign_ports_if_used\x18\v \x01(\bH\x05R\x13reassignPortsIfUsed\x88\x01\x01\x12(\n" +
	"\rdynamic_ports\x18\f \x01(\bH\x06R\fdynamicPorts\x88\x01\x01\x1aD\n" +
	"\x16CustomNodeConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11ChainConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13UpgradeConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_num_nodesB\x16\n" +
	"\x14_whitelisted_subnetsB\x15\n" +
	"\x13_global_node_configB\x10\n" +
	"\x0e_root_data_dirB\r\n" +
	"\v_plugin_dirB\x19\n" +
	"\x17_reassign_ports_if_usedB\x10\n" +
	"\x0e_dynamic_ports\"F\n" +
	"\rStartResponse\x125\n" +
	"\fcluster_info\x18\x01 \x01(\v2\x12.rpcpb.ClusterInfoR\vclusterInfo\"\xbf\x01\n" +
	"\x0eBlockchainSpec\x12\x17\n" +
	"\avm_name\x18\x01 \x01(\tR\x06vmName\x12\x18\n" +
	"\agenesis\x18\x02 \x01(\tR\agenesis\x12 \n" +
	"\tsubnet_id\x18\x03 \x01(\tH\x00R\bsubnetId\x88\x01\x01\x12!\n" +
	"\fchain_config\x18\x04 \x01(\tR\vchainConfig\x12'\n" +
	"\x0fnetwork_upgrade\x18\x05 \x01(\tR\x0enetworkUpgradeB\f\n" +
	"\n" +
	"_subnet_id\"\\\n" +
	"\x18CreateBlockchainsRequest\x12@\n" +
	"\x10blockchain_specs\x18\x01 \x03(\v2\x15.rpcpb.BlockchainSpecR\x0fblockchainSpecs\"R\n" +
	"\x19CreateBlockchainsResponse\x125\n" +
	"\fcluster_info\x18\x01 \x01(\v2\x12.rpcpb.ClusterInfoR\vclusterInfo\"L\n" +
	"\x14CreateSubnetsRequest\x12$\n" +
	"\vnum_subnets\x18\x01 \x01(\rH\x00R\n" +
	"numSubnets\x88\x01\x01B\x0e\n" +
	"\f_num_subnets\"N\n" +
	"\x15CreateSubnetsResponse\x125\n" +
	"\fcluster_info\x18\x01 \x01(\v2\x12.rpcpb.ClusterInfoR\vclusterInfo\"\x0f\n" +
	"\rHealthRequest\"G\n" +
	"\x0eHealthResponse\x125\n" +
	"\fcluster_info\x18\x01 \x01(\v2\x12.rpcpb.ClusterInfoR\vclusterInfo\"\r\n" +
	"\vURIsRequest\"\"\n" +
	"\fURIsResponse\x12\x12\n" +
	"\x04uris\x18\x01 \x03(\tR\x04uris\"\x0f\n" +
	"\rStatusRequest\"G\n" +
	"\x0eStatusResponse\x125\n" +
	"\fcluster_info\x18\x01 \x01(\v2\x12.rpcpb.ClusterInfoR\vclusterInfo\":\n" +
	"\x13StreamStatusRequest\x12#\n" +
	"\rpush_interval\x18\x01 \x01(\x03R\fpushInterval\"M\n" +
	"\x14StreamStatusResponse\x125\n" +
	"\fcluster_info\x18\x01 \x01(\v2\x12.rpcpb.ClusterInfoR\vclusterInfo\"\xd4\x03\n" +
	"\x12RestartNodeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\texec_path\x18\x02 \x01(\tH\x00R\bexecPath\x88\x01\x01\x124\n" +
	"\x13whitelisted_subnets\x18\x03 \x01(\tH\x01R\x12whitelistedSubnets\x88\x01\x01\x12P\n" +
	"\rchain_configs\x18\x04 \x03(\v2+.rpcpb.RestartNodeRequest.ChainConfigsEntryR\fchainConfigs\x12V\n" +
	"\x0fupgrade_configs\x18\x05 \x03(\v2-.rpcpb.RestartNodeRequest.UpgradeConfigsEntryR\x0eupgradeConfigs\x1a?\n" +
	"\x11ChainConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13UpgradeConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_exec_pathB\x16\n" +
	"\x14_whitelisted_subnets\"L\n" +
	"\x13RestartNodeResponse\x125\n" +
	"\fcluster_info\x18\x01 \x01(\v2\x12.rpcpb.ClusterInfoR\vclusterInfo\"'\n" +
	"\x11RemoveNodeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"K\n" +
	"\x12RemoveNodeResponse\x125\n" +
	"\fcluster_info\x18\x01 \x01(\v2\x12.rpcpb.ClusterInfoR\vclusterInfo\"\x9d\x03\n" +
	"\x0eAddNodeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\texec_path\x18\x02 \x01(\tR\bexecPath\x12$\n" +
	"\vnode_config\x18\x03 \x01(\tH\x00R\n" +
	"nodeConfig\x88\x01\x01\x12L\n" +
	"\rchain_configs\x18\x04 \x03(\v2'.rpcpb.AddNodeRequest.ChainConfigsEntryR\fchainConfigs\x12R\n" +
	"\x0fupgrade_configs\x18\x05 \x03(\v2).rpcpb.AddNodeRequest.UpgradeConfigsEntryR\x0eupgradeConfigs\x1a?\n" +
	"\x11ChainConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13UpgradeConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_node_config\"H\n" +
	"\x0fAddNodeResponse\x125\n" +
	"\fcluster_info\x18\x01 \x01(\v2\x12.rpcpb.ClusterInfoR\vclusterInfo\"\r\n" +
	"\vStopRequest\"E\n" +
	"\fStopResponse\x125\n" +
	"\fcluster_info\x18\x01 \x01(\v2\x12.rpcpb.ClusterInfoR\vclusterInfo\"0\n" +
	"\x11AttachPeerRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\"\x92\x01\n" +
	"\x12AttachPeerResponse\x125\n" +
	"\fcluster_info\x18\x01 \x01(\v2\x12.rpcpb.ClusterInfoR\vclusterInfo\x12E\n" +
	"\x12attached_peer_info\x18\x02 \x01(\v2\x17.rpcpb.AttachedPeerInfoR\x10attachedPeerInfo\"x\n" +
	"\x1aSendOutboundMessageRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\rR\x02op\x12\x14\n" +
	"\x05bytes\x18\x04 \x01(\fR\x05bytes\"1\n" +
	"\x1bSendOutboundMessageResponse\x12\x12\n" +
	"\x04sent\x18\x01 \x01(\bR\x04sent\":\n" +
	"\x13SaveSnapshotRequest\x12#\n" +
	"\rsnapshot_name\x18\x01 \x01(\tR\fsnapshotName\";\n" +
	"\x14SaveSnapshotResponse\x12#\n" +
	"\rsnapshot_path\x18\x01 \x01(\tR\fsnapshotPath\"\xa7\x05\n" +
	"\x13LoadSnapshotRequest\x12#\n" +
	"\rsnapshot_name\x18\x01 \x01(\tR\fsnapshotName\x12 \n" +
	"\texec_path\x18\x02 \x01(\tH\x00R\bexecPath\x88\x01\x01\x12\"\n" +
	"\n" +
	"plugin_dir\x18\x03 \x01(\tH\x01R\tpluginDir\x88\x01\x01\x12'\n" +
	"\rroot_data_dir\x18\x04 \x01(\tH\x02R\vrootDataDir\x88\x01\x01\x12Q\n" +
	"\rchain_configs\x18\x05 \x03(\v2,.rpcpb.LoadSnapshotRequest.ChainConfigsEntryR\fchainConfigs\x12W\n" +
	"\x0fupgrade_configs\x18\x06 \x03(\v2..rpcpb.LoadSnapshotRequest.UpgradeConfigsEntryR\x0eupgradeConfigs\x121\n" +
	"\x12global_node_config\x18\a \x01(\tH\x03R\x10globalNodeConfig\x88\x01\x01\x128\n" +
	"\x16reassign_ports_if_used\x18\b \x01(\bH\x04R\x13reassignPortsIfUsed\x88\x01\x01\x1a?\n" +
	"\x11ChainConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13UpgradeConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_exec_pathB\r\n" +
	"\v_plugin_dirB\x10\n" +
	"\x0e_root_data_dirB\x15\n" +
	"\x13_global_node_configB\x19\n" +
	"\x17_reassign_ports_if_used\"M\n" +
	"\x14LoadSnapshotResponse\x125\n" +
	"\fcluster_info\x18\x01 \x01(\v2\x12.rpcpb.ClusterInfoR\vclusterInfo\"<\n" +
	"\x15RemoveSnapshotRequest\x12#\n" +
	"\rsnapshot_name\x18\x01 \x01(\tR\fsnapshotName\"\x18\n" +
	"\x16RemoveSnapshotResponse\"\x19\n" +
	"\x17GetSnapshotNamesRequest\"A\n" +
	"\x18GetSnapshotNamesResponse\x12%\n" +
	"\x0esnapshot_names\x18\x01 \x03(\tR\rsnapshotNames2@\n" +
	"\vPingService\x121\n" +
	"\x04Ping\x12\x12.rpcpb.PingRequest\x1a\x13.rpcpb.PingResponse\"\x002\xbf\t\n" +
	"\x0eControlService\x124\n" +
	"\x05Start\x12\x13.rpcpb.StartRequest\x1a\x14.rpcpb.StartResponse\"\x00\x12X\n" +
	"\x11CreateBlockchains\x12\x1f.rpcpb.CreateBlockchainsRequest\x1a .rpcpb.CreateBlockchainsResponse\"\x00\x12L\n" +
	"\rCreateSubnets\x12\x1b.rpcpb.CreateSubnetsRequest\x1a\x1c.rpcpb.CreateSubnetsResponse\"\x00\x127\n" +
	"\x06Health\x12\x14.rpcpb.HealthRequest\x1a\x15.rpcpb.HealthResponse\"\x00\x121\n" +
	"\x04URIs\x12\x12.rpcpb.URIsRequest\x1a\x13.rpcpb.URIsResponse\"\x00\x127\n" +
	"\x06Status\x12\x14.rpcpb.StatusRequest\x1a\x15.rpcpb.StatusResponse\"\x00\x12K\n" +
	"\fStreamStatus\x12\x1a.rpcpb.StreamStatusRequest\x1a\x1b.rpcpb.StreamStatusResponse\"\x000\x01\x12C\n" +
	"\n" +
	"RemoveNode\x12\x18.rpcpb.RemoveNodeRequest\x1a\x19.rpcpb.RemoveNodeResponse\"\x00\x12:\n" +
	"\aAddNode\x12\x15.rpcpb.AddNodeRequest\x1a\x16.rpcpb.AddNodeResponse\"\x00\x12F\n" +
	"\vRestartNode\x12\x19.rpcpb.RestartNodeRequest\x1a\x1a.rpcpb.RestartNodeResponse\"\x00\x121\n" +
	"\x04Stop\x12\x12.rpcpb.StopRequest\x1a\x13.rpcpb.StopResponse\"\x00\x12C\n" +
	"\n" +
	"AttachPeer\x12\x18.rpcpb.AttachPeerRequest\x1a\x19.rpcpb.AttachPeerResponse\"\x00\x12^\n" +
	"\x13SendOutboundMessage\x12!.rpcpb.SendOutboundMessageRequest\x1a\".rpcpb.SendOutboundMessageResponse\"\x00\x12I\n" +
	"\fSaveSnapshot\x12\x1a.rpcpb.SaveSnapshotRequest\x1a\x1b.rpcpb.SaveSnapshotResponse\"\x00\x12I\n" +
	"\fLoadSnapshot\x12\x1a.rpcpb.LoadSnapshotRequest\x1a\x1b.rpcpb.LoadSnapshotResponse\"\x00\x12O\n" +
	"\x0eRemoveSnapshot\x12\x1c.rpcpb.RemoveSnapshotRequest\x1a\x1d.rpcpb.RemoveSnapshotResponse\"\x00\x12U\n" +
	"\x10GetSnapshotNames\x12\x1e.rpcpb.GetSnapshotNamesRequest\x1a\x1f.rpcpb.GetSnapshotNamesResponse\"\x00B\"Z github.com/luxfi/netrunner;rpcpbb\x06proto3"

var (
	file_rpcpb_rpc_proto_rawDescOnce sync.Once
	file_rpcpb_rpc_proto_rawDescData []byte
)

func file_rpcpb_rpc_proto_rawDescGZIP() []byte {
	file_rpcpb_rpc_proto_rawDescOnce.Do(func() {
		file_rpcpb_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpcpb_rpc_proto_rawDesc), len(file_rpcpb_rpc_proto_rawDesc)))
	})
	return file_rpcpb_rpc_proto_rawDescData
}

var file_rpcpb_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 54)
var file_rpcpb_rpc_proto_goTypes = []any{
	(*PingRequest)(nil),                 // 0: rpcpb.PingRequest
	(*PingResponse)(nil),                // 1: rpcpb.PingResponse
	(*ClusterInfo)(nil),                 // 2: rpcpb.ClusterInfo
	(*CustomChainInfo)(nil),             // 3: rpcpb.CustomChainInfo
	(*NodeInfo)(nil),                    // 4: rpcpb.NodeInfo
	(*AttachedPeerInfo)(nil),            // 5: rpcpb.AttachedPeerInfo
	(*ListOfAttachedPeerInfo)(nil),      // 6: rpcpb.ListOfAttachedPeerInfo
	(*StartRequest)(nil),                // 7: rpcpb.StartRequest
	(*StartResponse)(nil),               // 8: rpcpb.StartResponse
	(*BlockchainSpec)(nil),              // 9: rpcpb.BlockchainSpec
	(*CreateBlockchainsRequest)(nil),    // 10: rpcpb.CreateBlockchainsRequest
	(*CreateBlockchainsResponse)(nil),   // 11: rpcpb.CreateBlockchainsResponse
	(*CreateSubnetsRequest)(nil),        // 12: rpcpb.CreateSubnetsRequest
	(*CreateSubnetsResponse)(nil),       // 13: rpcpb.CreateSubnetsResponse
	(*HealthRequest)(nil),               // 14: rpcpb.HealthRequest
	(*HealthResponse)(nil),              // 15: rpcpb.HealthResponse
	(*URIsRequest)(nil),                 // 16: rpcpb.URIsRequest
	(*URIsResponse)(nil),                // 17: rpcpb.URIsResponse
	(*StatusRequest)(nil),               // 18: rpcpb.StatusRequest
	(*StatusResponse)(nil),              // 19: rpcpb.StatusResponse
	(*StreamStatusRequest)(nil),         // 20: rpcpb.StreamStatusRequest
	(*StreamStatusResponse)(nil),        // 21: rpcpb.StreamStatusResponse
	(*RestartNodeRequest)(nil),          // 22: rpcpb.RestartNodeRequest
	(*RestartNodeResponse)(nil),         // 23: rpcpb.RestartNodeResponse
	(*RemoveNodeRequest)(nil),           // 24: rpcpb.RemoveNodeRequest
	(*RemoveNodeResponse)(nil),          // 25: rpcpb.RemoveNodeResponse
	(*AddNodeRequest)(nil),              // 26: rpcpb.AddNodeRequest
	(*AddNodeResponse)(nil),             // 27: rpcpb.AddNodeResponse
	(*StopRequest)(nil),                 // 28: rpcpb.StopRequest
	(*StopResponse)(nil),                // 29: rpcpb.StopResponse
	(*AttachPeerRequest)(nil),           // 30: rpcpb.AttachPeerRequest
	(*AttachPeerResponse)(nil),          // 31: rpcpb.AttachPeerResponse
	(*SendOutboundMessageRequest)(nil),  // 32: rpcpb.SendOutboundMessageRequest
	(*SendOutboundMessageResponse)(nil), // 33: rpcpb.SendOutboundMessageResponse
	(*SaveSnapshotRequest)(nil),         // 34: rpcpb.SaveSnapshotRequest
	(*SaveSnapshotResponse)(nil),        // 35: rpcpb.SaveSnapshotResponse
	(*LoadSnapshotRequest)(nil),         // 36: rpcpb.LoadSnapshotRequest
	(*LoadSnapshotResponse)(nil),        // 37: rpcpb.LoadSnapshotResponse
	(*RemoveSnapshotRequest)(nil),       // 38: rpcpb.RemoveSnapshotRequest
	(*RemoveSnapshotResponse)(nil),      // 39: rpcpb.RemoveSnapshotResponse
	(*GetSnapshotNamesRequest)(nil),     // 40: rpcpb.GetSnapshotNamesRequest
	(*GetSnapshotNamesResponse)(nil),    // 41: rpcpb.GetSnapshotNamesResponse
	nil,                                 // 42: rpcpb.ClusterInfo.NodeInfosEntry
	nil,                                 // 43: rpcpb.ClusterInfo.AttachedPeerInfosEntry
	nil,                                 // 44: rpcpb.ClusterInfo.CustomChainsEntry
	nil,                                 // 45: rpcpb.StartRequest.CustomNodeConfigsEntry
	nil,                                 // 46: rpcpb.StartRequest.ChainConfigsEntry
	nil,                                 // 47: rpcpb.StartRequest.UpgradeConfigsEntry
	nil,                                 // 48: rpcpb.RestartNodeRequest.ChainConfigsEntry
	nil,                                 // 49: rpcpb.RestartNodeRequest.UpgradeConfigsEntry
	nil,                                 // 50: rpcpb.AddNodeRequest.ChainConfigsEntry
	nil,                                 // 51: rpcpb.AddNodeRequest.UpgradeConfigsEntry
	nil,                                 // 52: rpcpb.LoadSnapshotRequest.ChainConfigsEntry
	nil,                                 // 53: rpcpb.LoadSnapshotRequest.UpgradeConfigsEntry
}
var file_rpcpb_rpc_proto_depIdxs = []int32{
	42, // 0: rpcpb.ClusterInfo.node_infos:type_name -> rpcpb.ClusterInfo.NodeInfosEntry
	43, // 1: rpcpb.ClusterInfo.attached_peer_infos:type_name -> rpcpb.ClusterInfo.AttachedPeerInfosEntry
	44, // 2: rpcpb.ClusterInfo.custom_chains:type_name -> rpcpb.ClusterInfo.CustomChainsEntry
	5,  // 3: rpcpb.ListOfAttachedPeerInfo.peers:type_name -> rpcpb.AttachedPeerInfo
	9,  // 4: rpcpb.StartRequest.blockchain_specs:type_name -> rpcpb.BlockchainSpec
	45, // 5: rpcpb.StartRequest.custom_node_configs:type_name -> rpcpb.StartRequest.CustomNodeConfigsEntry
	46, // 6: rpcpb.StartRequest.chain_configs:type_name -> rpcpb.StartRequest.ChainConfigsEntry
	47, // 7: rpcpb.StartRequest.upgrade_configs:type_name -> rpcpb.StartRequest.UpgradeConfigsEntry
	2,  // 8: rpcpb.StartResponse.cluster_info:type_name -> rpcpb.ClusterInfo
	9,  // 9: rpcpb.CreateBlockchainsRequest.blockchain_specs:type_name -> rpcpb.BlockchainSpec
	2,  // 10: rpcpb.CreateBlockchainsResponse.cluster_info:type_name -> rpcpb.ClusterInfo
	2,  // 11: rpcpb.CreateSubnetsResponse.cluster_info:type_name -> rpcpb.ClusterInfo
	2,  // 12: rpcpb.HealthResponse.cluster_info:type_name -> rpcpb.ClusterInfo
	2,  // 13: rpcpb.StatusResponse.cluster_info:type_name -> rpcpb.ClusterInfo
	2,  // 14: rpcpb.StreamStatusResponse.cluster_info:type_name -> rpcpb.ClusterInfo
	48, // 15: rpcpb.RestartNodeRequest.chain_configs:type_name -> rpcpb.RestartNodeRequest.ChainConfigsEntry
	49, // 16: rpcpb.RestartNodeRequest.upgrade_configs:type_name -> rpcpb.RestartNodeRequest.UpgradeConfigsEntry
	2,  // 17: rpcpb.RestartNodeResponse.cluster_info:type_name -> rpcpb.ClusterInfo
	2,  // 18: rpcpb.RemoveNodeResponse.cluster_info:type_name -> rpcpb.ClusterInfo
	50, // 19: rpcpb.AddNodeRequest.chain_configs:type_name -> rpcpb.AddNodeRequest.ChainConfigsEntry
	51, // 20: rpcpb.AddNodeRequest.upgrade_configs:type_name -> rpcpb.AddNodeRequest.UpgradeConfigsEntry
	2,  // 21: rpcpb.AddNodeResponse.cluster_info:type_name -> rpcpb.ClusterInfo
	2,  // 22: rpcpb.StopResponse.cluster_info:type_name -> rpcpb.ClusterInfo
	2,  // 23: rpcpb.AttachPeerResponse.cluster_info:type_name -> rpcpb.ClusterInfo
	5,  // 24: rpcpb.AttachPeerResponse.attached_peer_info:type_name -> rpcpb.AttachedPeerInfo
	52, // 25: rpcpb.LoadSnapshotRequest.chain_configs:type_name -> rpcpb.LoadSnapshotRequest.ChainConfigsEntry
	53, // 26: rpcpb.LoadSnapshotRequest.upgrade_configs:type_name -> rpcpb.LoadSnapshotRequest.UpgradeConfigsEntry
	2,  // 27: rpcpb.LoadSnapshotResponse.cluster_info:type_name -> rpcpb.ClusterInfo
	4,  // 28: rpcpb.ClusterInfo.NodeInfosEntry.value:type_name -> rpcpb.NodeInfo
	6,  // 29: rpcpb.ClusterInfo.AttachedPeerInfosEntry.value:type_name -> rpcpb.ListOfAttachedPeerInfo
	3,  // 30: rpcpb.ClusterInfo.CustomChainsEntry.value:type_name -> rpcpb.CustomChainInfo
	0,  // 31: rpcpb.PingService.Ping:input_type -> rpcpb.PingRequest
	7,  // 32: rpcpb.ControlService.Start:input_type -> rpcpb.StartRequest
	10, // 33: rpcpb.ControlService.CreateBlockchains:input_type -> rpcpb.CreateBlockchainsRequest
	12, // 34: rpcpb.ControlService.CreateSubnets:input_type -> rpcpb.CreateSubnetsRequest
	14, // 35: rpcpb.ControlService.Health:input_type -> rpcpb.HealthRequest
	16, // 36: rpcpb.ControlService.URIs:input_type -> rpcpb.URIsRequest
	18, // 37: rpcpb.ControlService.Status:input_type -> rpcpb.StatusRequest
	20, // 38: rpcpb.ControlService.StreamStatus:input_type -> rpcpb.StreamStatusRequest
	24, // 39: rpcpb.ControlService.RemoveNode:input_type -> rpcpb.RemoveNodeRequest
	26, // 40: rpcpb.ControlService.AddNode:input_type -> rpcpb.AddNodeRequest
	22, // 41: rpcpb.ControlService.RestartNode:input_type -> rpcpb.RestartNodeRequest
	28, // 42: rpcpb.ControlService.Stop:input_type -> rpcpb.StopRequest
	30, // 43: rpcpb.ControlService.AttachPeer:input_type -> rpcpb.AttachPeerRequest
	32, // 44: rpcpb.ControlService.SendOutboundMessage:input_type -> rpcpb.SendOutboundMessageRequest
	34, // 45: rpcpb.ControlService.SaveSnapshot:input_type -> rpcpb.SaveSnapshotRequest
	36, // 46: rpcpb.ControlService.LoadSnapshot:input_type -> rpcpb.LoadSnapshotRequest
	38, // 47: rpcpb.ControlService.RemoveSnapshot:input_type -> rpcpb.RemoveSnapshotRequest
	40, // 48: rpcpb.ControlService.GetSnapshotNames:input_type -> rpcpb.GetSnapshotNamesRequest
	1,  // 49: rpcpb.PingService.Ping:output_type -> rpcpb.PingResponse
	8,  // 50: rpcpb.ControlService.Start:output_type -> rpcpb.StartResponse
	11, // 51: rpcpb.ControlService.CreateBlockchains:output_type -> rpcpb.CreateBlockchainsResponse
	13, // 52: rpcpb.ControlService.CreateSubnets:output_type -> rpcpb.CreateSubnetsResponse
	15, // 53: rpcpb.ControlService.Health:output_type -> rpcpb.HealthResponse
	17, // 54: rpcpb.ControlService.URIs:output_type -> rpcpb.URIsResponse
	19, // 55: rpcpb.ControlService.Status:output_type -> rpcpb.StatusResponse
	21, // 56: rpcpb.ControlService.StreamStatus:output_type -> rpcpb.StreamStatusResponse
	25, // 57: rpcpb.ControlService.RemoveNode:output_type -> rpcpb.RemoveNodeResponse
	27, // 58: rpcpb.ControlService.AddNode:output_type -> rpcpb.AddNodeResponse
	23, // 59: rpcpb.ControlService.RestartNode:output_type -> rpcpb.RestartNodeResponse
	29, // 60: rpcpb.ControlService.Stop:output_type -> rpcpb.StopResponse
	31, // 61: rpcpb.ControlService.AttachPeer:output_type -> rpcpb.AttachPeerResponse
	33, // 62: rpcpb.ControlService.SendOutboundMessage:output_type -> rpcpb.SendOutboundMessageResponse
	35, // 63: rpcpb.ControlService.SaveSnapshot:output_type -> rpcpb.SaveSnapshotResponse
	37, // 64: rpcpb.ControlService.LoadSnapshot:output_type -> rpcpb.LoadSnapshotResponse
	39, // 65: rpcpb.ControlService.RemoveSnapshot:output_type -> rpcpb.RemoveSnapshotResponse
	41, // 66: rpcpb.ControlService.GetSnapshotNames:output_type -> rpcpb.GetSnapshotNamesResponse
	49, // [49:67] is the sub-list for method output_type
	31, // [31:49] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_rpcpb_rpc_proto_init() }
func file_rpcpb_rpc_proto_init() {
	if File_rpcpb_rpc_proto != nil {
		return
	}
	file_rpcpb_rpc_proto_msgTypes[7].OneofWrappers = []any{}
	file_rpcpb_rpc_proto_msgTypes[9].OneofWrappers = []any{}
	file_rpcpb_rpc_proto_msgTypes[12].OneofWrappers = []any{}
	file_rpcpb_rpc_proto_msgTypes[22].OneofWrappers = []any{}
	file_rpcpb_rpc_proto_msgTypes[26].OneofWrappers = []any{}
	file_rpcpb_rpc_proto_msgTypes[36].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcpb_rpc_proto_rawDesc), len(file_rpcpb_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   54,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_rpcpb_rpc_proto_goTypes,
		DependencyIndexes: file_rpcpb_rpc_proto_depIdxs,
		MessageInfos:      file_rpcpb_rpc_proto_msgTypes,
	}.Build()
	File_rpcpb_rpc_proto = out.File
	file_rpcpb_rpc_proto_goTypes = nil
	file_rpcpb_rpc_proto_depIdxs = nil
}
